config:
  enable_pull_requests_from_forks: false
pipelines:
  /feature_.*/:
    triggers:
    - "COMMIT"
    stages: []
  master:
    triggers:
    - "COMMIT"
    stages:
    - name: "Code Validation stage"
      steps:
      - type: "JOB"
        name: "control-repo-manifest-validate"
        concurrent_compilations: 0
        all_deployments: false
      - type: "JOB"
        name: "control-repo-hiera-syntax-validate"
        concurrent_compilations: 0
        all_deployments: false
      - type: "JOB"
        name: "control-repo-template-syntax-validate"
        concurrent_compilations: 0
        all_deployments: false
      - type: "JOB"
        name: "control-repo-puppetfile-syntax-validate"
        concurrent_compilations: 0
        all_deployments: false
      auto_promote: "all_succeeded"
    - name: "Impact Analysis stage"
      steps:
      - type: "IMPACT_ANALYSIS"
        concurrent_compilations: 10
        all_deployments: true
      - type: "PULL_REQUEST_GATE"
        concurrent_compilations: 0
        all_deployments: false
      auto_promote: false
    - name: "Deployment stage"
      steps:
      - type: "DEPLOYMENT"
        policy:
          name: "cd4pe_deployments::direct"
        parameters:
          noop: false
        timeout: 3600000
        concurrent_compilations: 0
        all_deployments: false
        pe_server: "gitlab"
        target:
          type: "NODE_GROUP"
          node_group_id: "ea8eb9f8-1b36-4f80-aef4-1a85aca546d0"
      auto_promote: false
spec_version: "V1"

